server:
  port: 8081
spring:
  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  redis:
    cache.clusterNodes: 192.168.136.6:7000,192.168.136.6:7001,192.168.136.6:7002,192.168.136.6:8001,192.168.136.6:8002,192.168.136.6:8003
    cache.commandTimeout: 5000



#mybatis配置
mybatis:
  #mapper配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl #这个不打印查询结果



